apiVersion: v2
name: odh-observability
description: Standalone monitoring module operator for Open Data Hub
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - monitoring
  - observability
  - opendatahub
home: https://github.com/opendatahub-io/odh-observability
sources:
  - https://github.com/opendatahub-io/odh-observability
