apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: data-science-collector-monitor
  namespace: {{.Namespace}}
spec:
  endpoints:
    - port: monitoring
      scheme: https
      tlsConfig:
        caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
        serverName: "data-science-collector-collector-monitoring.{{.Namespace}}.svc"
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  namespaceSelector:
    matchNames:
      - {{.Namespace}}
  selector:
    matchLabels:
      app.kubernetes.io/component: opentelemetry-collector
      app.kubernetes.io/instance: {{.Namespace}}.data-science-collector
      app.kubernetes.io/managed-by: opentelemetry-operator
      app.kubernetes.io/part-of: opentelemetry
      operator.opentelemetry.io/collector-service-type: base

---
apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: data-science-prometheus-monitor
  namespace: {{.Namespace}}
spec:
  endpoints:
    - port: prometheus
      scheme: https
      tlsConfig:
        caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
        serverName: "data-science-collector-collector-monitoring.{{.Namespace}}.svc"
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  namespaceSelector:
    matchNames:
      - {{.Namespace}}
  selector:
    matchLabels:
      app.kubernetes.io/component: opentelemetry-collector
      app.kubernetes.io/instance: {{.Namespace}}.data-science-collector
      app.kubernetes.io/managed-by: opentelemetry-operator
      app.kubernetes.io/part-of: opentelemetry
      operator.opentelemetry.io/collector-service-type: base
