---
# for prometheus container codeflare rules
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  template:
    spec:
      containers:
        - name: prometheus
          volumeMounts:
            - mountPath: /etc/prometheus
              name: prometheus-ray-config
      volumes:
        - name: prometheus-ray-config
          configMap:
            name: prometheus-ray


