apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rhods-monitor-federation
  namespace: redhat-ods-monitoring
  labels:
    monitor-component: rhods-resources
    team: rhods
spec:
  endpoints:
    - authorization:
        type: Bearer
        credentialsFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      params:
        "match[]":
          - '{__name__= "rhods_total_users"}'
          - '{__name__= "rhods_active_users"}'
          - '{__name__= "rhods_aggregate_availability"}'
          - ALERTS{alertname!="DeadManSnitch", alertstate="firing"}
      path: /federate
      port: https
      scheme: https
      tlsConfig:
        caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
        serverName: "prometheus.redhat-ods-monitoring.svc"
      scrapeTimeout: 10s
      interval: 30s
  namespaceSelector:
    matchNames:
      - <odh_monitoring_project>
  selector:
    matchLabels:
      app: prometheus
