---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - mlflow-artifact-connection
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - console.openshift.io
  resources:
  - consolelinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mlflow.kubeflow.org
  resources:
  - mlflowconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mlflow.opendatahub.io
  resources:
  - mlflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mlflow.opendatahub.io
  resources:
  - mlflows/finalizers
  verbs:
  - update
- apiGroups:
  - mlflow.opendatahub.io
  resources:
  - mlflows/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
