# ClusterRole for the Spark Operator controller
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-operator-controller
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/component: controller
rules:
# Core resources
- apiGroups: [""]
  resources:
  - pods
  - configmaps
  - services
  - persistentvolumeclaims
  verbs: [create, delete, deletecollection, get, list, patch, update, watch]
- apiGroups: [""]
  resources: [events]
  verbs: [create, patch, update]
- apiGroups: [""]
  resources: [nodes]
  verbs: [get]
- apiGroups: [""]
  resources: [resourcequotas]
  verbs: [get, list, watch]
# CRDs
- apiGroups: [apiextensions.k8s.io]
  resources: [customresourcedefinitions]
  verbs: [get]
# Ingresses
- apiGroups: [extensions, networking.k8s.io]
  resources: [ingresses]
  verbs: [create, delete, get, list, update, watch]
# SparkApplication CRDs
- apiGroups: [sparkoperator.k8s.io]
  resources: [sparkapplications, scheduledsparkapplications, sparkconnects]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [sparkoperator.k8s.io]
  resources: [sparkapplications/finalizers, scheduledsparkapplications/finalizers, sparkconnects/finalizers]
  verbs: [update]
- apiGroups: [sparkoperator.k8s.io]
  resources: [sparkapplications/status, scheduledsparkapplications/status, sparkconnects/status]
  verbs: [get, patch, update]