# Role for leader election coordination (namespace-scoped)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: controller
  namespace: system
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/component: controller
rules:
- apiGroups: [coordination.k8s.io]
  resources: [leases]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [""]
  resources: [events]
  verbs: [create, patch, update]
- apiGroups: [""]
  resources: [configmaps]
  verbs: [create, delete, get, list, patch, update, watch]