# RoleBinding for controller - connects Role to the controller ServiceAccount.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller  # References leader-election-role.yaml
  namespace: system
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/component: controller
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: controller
