# permissions for end users to edit llamastacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: llamastack-editor-role
rules:
- apiGroups:
  - llamastack.io
  resources:
  - llamastacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - llamastack.io
  resources:
  - llamastacks/status
  verbs:
  - get
