# permissions for end users to edit LlamaStackDistributions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: llsd-editor-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - llamastack.io
  resources:
  - llamastackdistributions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - llamastack.io
  resources:
  - llamastackdistributions/status
  verbs:
  - get
