# for prometheus container codeflare rules
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: redhat-ods-monitoring
spec:
  template:
    spec:
      containers:
        - name: prometheus
          volumeMounts:
            - mountPath: /etc/prometheus
              name: prometheus-codeflare-config
      volumes:
        - name: prometheus-codeflare-config
          configMap:
            name: prometheus-codeflare
