# Role for webhook component in operator namespace.
# Webhook needs permissions for managing TLS secrets and leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webhook
  namespace: system
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/component: webhook
rules:
  # Secrets - webhook generates and stores its TLS certificates
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - spark-operator-webhook-certs
    verbs:
      - get
      - update
  # Leader election - for HA coordination
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    resourceNames:
      - spark-operator-webhook-lock
    verbs:
      - get
      - update
  # Events - for recording webhook activity
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
