# RoleBinding for webhook - connects Role to the webhook ServiceAccount.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webhook
  namespace: system
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/component: webhook
subjects:
  - kind: ServiceAccount
    name: webhook
    namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webhook
