# ServiceAccount for the webhook component.
# The webhook intercepts pod creation requests and mutates/validates SparkApplications.
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: webhook
  namespace: system
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/component: webhook
