# ------------------------------------------------------------------------------
# Custom Resource Definitions (CRDs) for Gateway API Inference Extension (GIE)
#
# This deploys the GIE CRDs from the local directory.
#
# **Warning**: CRDs are cluster-level, so in a shared development environment
# this needs to be done in a controlled and communicated manner.
# ------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubernetes-sigs/gateway-api-inference-extension/config/crd?ref=v0.5.0