apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opendatahub

resources:
  - ../../default

patches:
  # patch to remove default `system` namespace in ../../manager/manager.yaml
  - path: delete-namespace.yaml

configMapGenerator:
  - name: params
    envs:
      - params.env

replacements:
  - source:
      kind: ConfigMap
      name: params
      fieldPath: data.RELATED_IMAGE_ODH_LLAMASTACK_OPERATOR
    targets:
      - select:
          kind: Deployment
          name: controller-manager
        fieldPaths:
          - spec.template.spec.containers.[name=manager].image
  - source:
      kind: ConfigMap
      name: params
      fieldPath: data.OPERATOR_VERSION
    targets:
      - select:
          kind: Deployment
          name: controller-manager
        fieldPaths:
          - spec.template.spec.containers.[name=manager].env.[name=OPERATOR_VERSION].value
  - source:
      kind: ConfigMap
      name: params
      fieldPath: data.RELATED_IMAGE_RH_DISTRIBUTION
    targets:
      - select:
          kind: Deployment
          name: controller-manager
        fieldPaths:
          - spec.template.spec.containers.[name=manager].env.[name=RELATED_IMAGE_RH_DISTRIBUTION].value
