---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/runtime-image: "true"
  annotations:
    opendatahub.io/runtime-image-url: "https://github.com//opendatahub-io/notebooks/tree/main/runtimes"
    opendatahub.io/runtime-image-name: "PyTorch with ROCm and Python 3.11 (UBI9)"
    opendatahub.io/runtime-image-desc: "ROCm optimized PyTorch runtime image for Elyra, enabling pipeline execution from Workbenches with PyTorch libraries and dependencies, supporting different runtimes for various pipeline nodes."
  name: runtime-rocm-pytorch
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations:
        # language=json
        opendatahub.io/runtime-image-metadata: |
          [
            {
              "display_name": "PyTorch with ROCm and Python 3.11 (UBI9)",
              "metadata": {
                "tags": [
                  "rocm-pytorch"
                ],
                "display_name": "PyTorch with ROCm and Python 3.11 (UBI9)",
                "image_name": "quay.io/modh/runtime-images@sha256:15652f6c1b6e048c77d8384220a13c5339135eec59233082c5f4b305ce5ffb01",
                "pull_policy": "IfNotPresent"
              },
              "schema_name": "runtime-image"
            }
          ]
        openshift.io/imported-from: quay.io/modh/runtime-images
      from:
        kind: DockerImage
        name: quay.io/modh/runtime-images@sha256:15652f6c1b6e048c77d8384220a13c5339135eec59233082c5f4b305ce5ffb01
      name: "rocm-pytorch"
      referencePolicy:
        type: Source
