---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/runtime-image: "true"
  annotations:
    # TODO: once the restraction takes a final shape need to update that url
    opendatahub.io/runtime-image-url: "https://github.com//opendatahub-io/notebooks/tree/main/runtimes"
    opendatahub.io/runtime-image-name: "TensorFlow with CUDA and Python 3.11 (UBI9)"
    opendatahub.io/runtime-image-desc: "TensorFlow runtime image for Elyra, enabling pipeline execution from Workbenches with TensorFlow libraries and dependencies, supporting different runtimes for various pipeline nodes."
  name: runtime-tensorflow
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations:
        # language=json
        opendatahub.io/runtime-image-metadata: |
          [
            {
              "display_name": "TensorFlow with CUDA and Python 3.11 (UBI9)",
              "metadata": {
                "tags": [
                  "tensorflow"
                ],
                "display_name": "TensorFlow with CUDA and Python 3.11 (UBI9)",
                "image_name": "quay.io/modh/runtime-images@sha256:7a1274d4c4b8bbf5554466e5427b88428954522c1652c27044e6f6f1d87b85fd",
                "pull_policy": "IfNotPresent"
              },
              "schema_name": "runtime-image"
            }
          ]
        openshift.io/imported-from: quay.io/modh/runtime-images
      from:
        kind: DockerImage
        name: quay.io/modh/runtime-images@sha256:7a1274d4c4b8bbf5554466e5427b88428954522c1652c27044e6f6f1d87b85fd
      name: "tensorflow"
      referencePolicy:
        type: Source
