apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-operator-controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace