apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: controller-manager-metrics-reader
  labels:
    app.kubernetes.io/name: kueue
    app.kubernetes.io/component: controller
  name: controller-manager-metrics-token
  namespace: system
type: kubernetes.io/service-account-token
