apiVersion: v1
kind: Service
metadata:
  name: metrics-service
spec:
  ports:
  - name: https-metrics
    port: 8443
    protocol: TCP
    targetPort: https-metrics
  selector:
    app.kubernetes.io/name: kueue
    app.kubernetes.io/part-of: kueue
status:
  loadBalancer: {}
