apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kueue
    app.kubernetes.io/component: controller
  namespace: system
  name: controller-manager-metrics-reader
