apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller-manager-read-metrics
subjects:
- kind: ServiceAccount
  name: controller-manager-metrics-reader  # Change this to your Prometheus service account
  namespace: system
roleRef:
  kind: ClusterRole
  name: metrics-reader
  apiGroup: rbac.authorization.k8s.io
