apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-operator
spec:
  template:
    spec:
      containers:
      - name:  training-operator
        image: $(image)
        args:
        - "--zap-log-level=2"
        - --pytorch-init-container-image
        - $(image)
        - "--webhook-secret-name"
        - "kubeflow-training-operator-webhook-cert"
        - "--webhook-service-name"
        - "kubeflow-training-operator"
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: kubeflow-training-operator-webhook-cert
