apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../test/clusterresources

patches:
  # We do not support ClusterServingRuntime, so we need to convert it to ServingRuntime for testing.
  - target:
      kind: ClusterServingRuntime
      version: v1alpha1
      group: serving.kserve.io
    patch: |-
      - op: replace
        path: /kind
        value: ServingRuntime
  # Remove the securityContext/runAsUser for the ServingRuntime, it's handled by Openshift.
  - target:
      kind: ServingRuntime
      version: v1alpha1
      group: serving.kserve.io
      name: kserve-torchserve
    patch: |-
      - op: remove
        path: /spec/containers/0/securityContext/runAsUser
  - target:
      kind: ServingRuntime
      version: v1alpha1
      group: serving.kserve.io
      name: kserve-tritonserver
    patch: |-
      - op: remove
        path: /spec/containers/0/securityContext/runAsUser
  - target:
      kind: ServingRuntime
      version: v1alpha1
      group: serving.kserve.io
      name: kserve-tensorflow-serving
    patch: |-
      - op: remove
        path: /spec/containers/0/securityContext/runAsUser
