apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manager.yaml

images:
  - name: ai-gateway-controller
    newName: quay.io/opendatahub/odh-ai-gateway-controller
    newTag: odh-stable
