nameOverride: ""
fullnameOverride: ""
config:
  platform-name: OpenDataHub
  platform-version: unknown
image:
  repository: quay.io/opendatahub/odh-feast-module-operator
  tag: odh-stable
leaderElect: true
replicas: 1
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 128Mi
serviceAccount: {}
