---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - mcp.kuadrant.io
  resources:
  - mcpgatewayextensions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mcp.kuadrant.io
  resources:
  - mcpserverregistrations
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - mcp.x-k8s.io
  resources:
  - mcpgatewaybindings
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - mcp.x-k8s.io
  resources:
  - mcpgatewaybindings/finalizers
  - mcpservers/finalizers
  verbs:
  - update
- apiGroups:
  - mcp.x-k8s.io
  resources:
  - mcpgatewaybindings/status
  - mcpservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mcp.x-k8s.io
  resources:
  - mcpservers
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - get
  - list
  - update
  - watch
