apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../default
- user-cluster-roles.yaml

namespace: opendatahub

patches:
- path: remove-namespace.yaml
- path: inferenceservice-config-patch.yaml
- path: set-resources-manager-patch.yaml
- path: config-llm-scheduler-patch.yaml
- path: config-llm-decode-template-patch.yaml
- path: config-llm-decode-worker-data-parallel-patch.yaml

replacements:
- source:
    kind: ConfigMap
    name: kserve-parameters
    fieldpath: data.kserve-controller
  targets:
  - select:
      kind: Deployment
      name: kserve-controller-manager
    fieldPaths:
    - spec.template.spec.containers.[name=manager].image

configMapGenerator:
- envs:
  - params.env
  name: kserve-parameters

generatorOptions:
  disableNameSuffixHash: true

vars:
- fieldref:
    fieldpath: data.kserve-storage-initializer
  name: kserve-storage-initializer
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kserve-parameters
- fieldref:
    fieldpath: data.kserve-agent
  name: kserve-agent
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kserve-parameters
- fieldref:
    fieldpath: data.kserve-router
  name: kserve-router
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kserve-parameters
- fieldref:
    fieldpath: data.oauth-proxy
  name: oauth-proxy
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kserve-parameters
- fieldref:
    fieldpath: data.kserve-llm-d-inference-scheduler
  name: kserve-llm-d-inference-scheduler
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kserve-parameters
- fieldref:
    fieldpath: data.kserve-llm-d-routing-sidecar
  name: kserve-llm-d-routing-sidecar
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kserve-parameters    

configurations:
  - params.yaml
