kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: openshift-ai-llminferenceservice-scc
priority: 10
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
allowedCapabilities:
  - "IPC_LOCK"
  - "SYS_RAWIO"
  - "NET_BIND_SERVICE"
requiredDropCapabilities:
- ALL
seccompProfiles:
- runtime/default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-ai-llminferenceservice-scc
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - openshift-ai-llminferenceservice-scc
    verbs:
      - use
