apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  # All RBAC will be applied under this service account in the deployment
  # namespace.
resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- user_cluster_roles.yaml
