apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rhods-prometheus-viewer
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: "<odh_monitoring_project>"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
