apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-science-pipelines-operator-controller-manager
  namespace: odh-applications
spec:
  template:
    spec:
      containers:
        - image: controller
          name: manager
