apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    crd/fake: "true"
  name: imagestreams.image.openshift.io
spec:
  group: image.openshift.io
  names:
    kind: ImageStream
    listKind: ImageStreamList
    singular: imagestream
    plural: imagestreams
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
