apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert
  namespace: system
spec:
  dnsNames:
  - kuberay-webhook-service.$(namespace).svc
  - kuberay-webhook-service.$(namespace).svc.cluster.local
