kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: run-as-ray-user
seLinuxContext:
  type: MustRunAs
defaultAllowPrivilegeEscalation: false
allowPrivilegeEscalation: false
seccompProfiles:
  - runtime/default
requiredDropCapabilities:
  - ALL
runAsUser:
  type: MustRunAs
  uid: 1000
fsGroup:
  type: MustRunAs
users:
  - 'system:serviceaccount:$(namespace):kuberay-operator'
