apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: notebook-controller-system
configMapGenerator:
- behavior: merge
  literals:
  - USE_ISTIO=false
  name: config
