---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-mcp-x-k8s-io-v1alpha1-mcpserver
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vmcpserver.mcp.x-k8s.io
  rules:
  - apiGroups:
    - mcp.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mcpservers
  sideEffects: None
