# ServiceAccount for the controller manager.
# When controller pods need to talk to Kubernetes API, they use this ServiceAccount.
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: controller
  namespace: system
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/component: controller
