apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "odh-observability.fullname" . }}
  namespace: {{ .Values.operatorNamespace }}
  labels:
    {{- include "odh-observability.labels" . | nindent 4 }}
