apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: kubeflow
configMapGenerator:
- behavior: merge
  literals:
  - USE_ISTIO=true
  - ISTIO_GATEWAY=kubeflow/kubeflow-gateway
  name: config
patches:
- path: patches/remove-namespace.yaml
