apiVersion: mcp.x-k8s.io/v1beta1
kind: MCPServer
metadata:
  labels:
    app.kubernetes.io/name: mcp-lifecycle-operator
    app.kubernetes.io/managed-by: kustomize
  name: mcpserver-restricted-ingress
spec:
  source:
    type: ContainerImage
    containerImage:
      ref: quay.io/containers/kubernetes_mcp_server:latest
  config:
    port: 8080
  network:
    ingressFrom:
      - namespaceSelector:
          matchLabels:
            mcp-client: "true"
