apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../prometheus
- ./default
- ./scripts
- ./quickstart.yaml
- ./rbac

namespace: opendatahub
configMapGenerator:
- envs:
  - params.env
  name: mesh-parameters
generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: ./crd/clusterservingruntime_patch_delete.yaml

vars:
- fieldref:
    fieldPath: metadata.namespace
  name: mesh-namespace
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mesh-parameters
- fieldref:
    fieldPath: data.odh-modelmesh
  name: odh-modelmesh
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mesh-parameters
- fieldref:
    fieldPath: data.odh-mm-rest-proxy
  name: odh-mm-rest-proxy
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mesh-parameters
- fieldref:
    fieldPath: data.odh-modelmesh-runtime-adapter
  name: odh-modelmesh-runtime-adapter
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mesh-parameters
- fieldref:
    fieldPath: data.odh-modelmesh-controller
  name: odh-modelmesh-controller
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mesh-parameters
- fieldref:
    fieldPath: data.ose-etcd
  name: ose-etcd
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mesh-parameters
- fieldref:
    fieldPath: data.ose-cli
  name: ose-cli
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mesh-parameters



configurations:
- params.yaml

labels:
- includeSelectors: true
  pairs:
    app: model-mesh
    app.kubernetes.io/part-of: model-mesh
