varReference:
  - path: metadata/namespace
    kind: ServiceAccount
  - path: metadata/name
    kind: ClusterRoleBinding
  - path: subjects/namespace
    kind: RoleBinding
  - path: spec/template/spec/containers[]/image
    kind: Deployment
  - path: data
    kind: ConfigMap
