apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: seaweedfs
spec:
  ingress:
  # Allow traffic from namespaces with the profile label
  - from:
    - namespaceSelector:
        matchExpressions:
        - key: app.kubernetes.io/part-of
          operator: In
          values:
          - $PROFILE_NAMESPACE_LABEL
    ports:
    - port: 8333
    - port: 8888
    - port: 9333
  # Allow traffic from istio-system
  - from:
    - namespaceSelector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
          - istio-system
    ports:
    - port: 8333
    - port: 8888
    - port: 9333
  # Allow traffic from the same namespace (for init job)
  - from:
    - podSelector: {}
    ports:
    - port: 8333
    - port: 8888
    - port: 9333
  podSelector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - seaweedfs
  policyTypes:
  - Ingress
