apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../openshift
- gateway.yaml
- gateway-route.yaml
- cert-secret.yaml
- smm.yaml
namespace: odh-notebook-controller-system

configMapGenerator:
- behavior: merge
  literals:
  - USE_ISTIO=true
  - ISTIO_GATEWAY=odh-notebook-controller-system/odh-gateway
  name: config

patches:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: istio-system
  target:
    group: route.openshift.io
    kind: Route
    name: opendatahub-odh-gateway
    namespace: odh-notebook-controller-system
    version: v1
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: istio-system
  target:
    kind: Secret
    name: odh-dashboard-cert
    namespace: odh-notebook-controller-system
    version: v1
- patch: |-
    - op: replace
      path: /spec/controlPlaneRef/namespace
      value: istio-system
  target:
    group: maistra.io
    kind: ServiceMeshMember
    name: default
    version: v1
