name: Operator Processor

on:
  workflow_dispatch:
  push:
    branches:
      - 'rhoai-2.1[6-9]+'
    paths:
      - build/operator-nudging.yaml


env:
  GITHUB_ORG: red-hat-data-services
  GITHUB_RKA_ORG: rhoai-rhtap

permissions:
  contents: write

jobs:
  operator-processor:
    runs-on: ubuntu-latest
      - name: Show params summary
        run: |
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.event.commits[0].author.name = ${{ github.event.commits[0].author.name }}"